### ISSUE TITLE
[Broken] Always blocks duplication, even for your own dupes, no matter what mode.

### ISSUE THREAD

**Issue by storm37000** [Divran/simple-e2-theft-protection#1]
Always blocks duplication, even for your own dupes, no matter what mode.

**Comment by Divran** [comment]
I only threw this together to get the people who complained to shut up. The correct answer is to not have abusive admins. Only promote people you trust. Even if you had a 100% foolproof way to prevent terrible admins from stealing E2s they would still be terrible admins for everything else.
